import type { Metadata } from "next";
import AdminNav from "@/components/AdminNav";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="container grid grid-cols-1 gap-4 lg:grid-cols-3 lg:gap-8 my-5">
  <div className="h-screen rounded-lg bg-gray-200">            
  <AdminNav />
</div>
  <div className="h-screen rounded-lg bg-gray-200 lg:col-span-2">  
  {children}
  </div>
</div>
  );
}
